package com.va1m.moskommunalbot.interaction;

/** Possible states during interaction with user */
public enum State {

    START,
    WAITING_FOR_LAST_COLD_WATER_METERS,
    WAITING_FOR_CURRENT_COLD_WATER_METERS,
    WAITING_FOR_LAST_HOT_WATER_METERS,
    WAITING_FOR_CURRENT_HOT_WATER_METERS,
    WAITING_FOR_LAST_ELECTRICITY_METERS,
    WAITING_FOR_CURRENT_ELECTRICITY_METERS,
    SHOWING_RESULTS
}
